export const APP_LIST_REQUEST = 'APP_LIST_REQUEST';
export const APP_LIST_SUCCESS = 'APP_LIST_SUCCESS';
export const APP_LIST_FAIL = 'APP_LIST_FAIL';

export const APP_DETAILS_REQUEST = 'APP_DETAILS_REQUEST';
export const APP_DETAILS_SUCCESS = 'APP_DETAILS_SUCCESS';
export const APP_DETAILS_FAIL = 'APP_DETAILS_FAIL';